Correctly fix lint error from #8651
Removing the null check breaks the build for dart 2.16.2 (used by flutter 2.10.5) which should still be supported. This reverts the change, and instead manually suppresses the error.

```
Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance.addPostFrameCallback(_sendEmailVerification);
```