in and array contains fixes
* bump core version to 0.4.1+4 (#1395)

* Remove deprecated firebase-core dependency (#1417)

* Remove deprecated firebase-core dependency

* [firebase_auth] getIdToken use actual refresh value instead of checking if object exists (#1334)

* getIdToken use actual refresh value instead of checking if object exists

* getIdToken refresh integration test

* update xcode to v11 (#1420)

* Update FirebaseApp creation in tests (#1406)

* [firebase_database] Support v2 android embedder. (#287)

* [firebase_remote_config] Support v2 android embedder. (#282)

* [CI] Add version to example apps (#1426)

* Add hardcode version to example apps

* [firebase_core] Add platform interface (#1324)

* Move firebase_core to firebase_core/firebase_core
* Add firebase_core_platform_interface package
* Update cirrus scripts and documentation

* [firebase_dynamic_links] Add support of expanding from short links (#1381)

* Fixes strict compilation errors. (#1331)

* Upgrade crashlytics to v2 plugin API (#1370)

* Upgraded Crashlytics to v2 of Flutter Plugins.

* Format documentation lists (See also & Errors) correctly (#298)

Fix documentation list format.

* [firebase_auth] Fix NoSuchMethodError exception in `reauthenticateWithCredential` (#237)

* [firebase_auth] Fix NoSuchMethodError exception

Fix NoSuchMethodError exception when calling FirebaseUser.reauthenticateWithCredential

* add integration test

* Fix analyzer warnings

Co-Authored-By: Collin Jackson <jackson@google.com>

* [cloud_firestore] [firebase_performance] fix analyzer warnings (#1453)

* fix analyzer warnings

* [CI] Skip flaky firebase_performance driver tests (#1452)

* Skip flaky firebase_performance driver tests

* [firebase_auth] Added missing Exception to the reauthenticateWithCredential docs (#1448) (#1449)

* Added missing Exception to the reauthenticateWithCredential docs (#1448)

* [firebase_remote_config] Bumps Android Firebase dependency to 19.0.3 (#1443)

* Bump AGP, Gradle & Google Services Plugin

* Bumps dependency to Firebase Config 19.0.3

* Replaces a deprecated method usage with the updated version

* [firebase_messaging] Use UNUserNotificationCenter for ios 10+ (#121)

* Use UNUserNotificationCenter for ios 10+

* Add swift documentation

* Move http test to README

* Update CONTRIBUTING.md (#1473)

Removes obsolete recommendations about removing mockito (which is now used in testing federated plugins).

* [firebase_core] Migrate to platform_interface (#1472)

* [firebase_messaging] Add an ArgumentError when passing invalid background message (#252)

* [firebase_dynamic_links] support v2 embedding (#1372)

* [cloud_firestore] Fix test that used FirebaseApp.channel (#1476)

* [cloud_firestore] Fix test that used FirebaseApp.channel

* dartfmt

* bump version

* Fixed dynamic issue

* Fixed dynamic issue

* FIxed Object to list of object mapping

* Fixed text result expectation

* Reverted some changes

* Satisfying formatter

* Added android x to pass the test

* Fixed changed log auto formatting