Ensure platform interfaces can only be extended, not implemented.
As expected, this breaks Web, for now:

```
00:07 +19 -23: /usr/local/google/home/dit/github/flutterfire/packages/cloud_firestore/cloud_firestore_web/test/document_reference_web_test.dart: DocumentReferenceWeb() snapshots [E]
  NoSuchMethodError: '_instanceToken'
  method not found
  Receiver: Instance of 'FieldValueFactoryWeb'
  Arguments: []
  package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 196:49              throw_
  package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 667:3           defaultNoSuchMethod
  package:dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 63:12                         noSuchMethod
  package:cloud_firestore_web/field_value_factory_web.dart 40:3                                     get [_instanceToken]
  package:plugin_platform_interface/plugin_platform_interface.dart 72:35                            verifyToken
  package:cloud_firestore_platform_interface/src/platform_interface/field_value_factory.dart 36:23  set instance
  package:cloud_firestore_web/firestore_web.dart 39:31                                              new
```