docs: Suggest the --flutter flag to melos bootstrap
Without this, melos bootstrap on a clean machine fails with:

	Running "flutter pub get" in workspace packages...
	Note: this may take a while in large workspaces such as this one.
	  - cloud_firestore_odm_generator
	    └> packages/cloud_firestore_odm/cloud_firestore_odm_generator
	    └> Failed to install.

	Resolving dependencies...
	Because every version of firebase_core_web from path depends on flutter_web_plugins from sdk which is forbidden, firebase_core_web from path is forbidden.
	So, because cloud_firestore_odm_generator depends on firebase_core_web from path, version solving failed.
	Flutter users should run `flutter pub get` instead of `dart pub get`.
	BootstrapException: Failed to install.: cloud_firestore_odm_generator at /Users/will/flutterfire/packages/cloud_firestore_odm/cloud_firestore_odm_generator.